@startuml EntityClassDiagram
abstract Item {
    -id:int
    -name:String
    -deleted:bool
    +toString():String
}

interface ItemArray{
    +getItem(id:int):item
    +newItem(item:Item)
    +deleteItem(item:Item)
    +getAll():Item[]
}

'Project Items
class Project extends Item {
    -neighborhood:String
    -flatType:enum (2-Room, 3-Room)
    -units:String
    -openingDate
    -closingDate
    -officerSlots:int
    -visibility:bool
    +getApplicantions():Application[]
    +getOfficerApplications():OfficerApplication[]
    +getEnquiries():Enquiry[]
    +getOfficers():Officer[]
    +getManager():Manager
}

class Application extends Item {
    -applicant:Applicant
    -project:Project
    -status:enum (pending, successful, unsuccessful, booked, withdrawing, withdrawn)
}

Application --> Applicant : Applicant
Application --> Project : Project

class OfficerApplication extends Application
OfficerApplication --> Officer : Officer
OfficerApplication --> Project : Project

class Enquiry extends Item {
    -project:Project
    -enquiry:String
    -reply:String
}
Enquiry --> Project : Project

'Users
class User extends Item{
    -type:enum
    -password:String
    -age:int
    -maritalStatus:enum
}

class Applicant extends User {
    +getApplication():Application
}

class Officer extends Applicant {
    -handledProject:Project (only 1)
    +getOfficerApplication():OfficerApplication
}

class Manager extends User {
    +getProject():Project
    +createProject():Project
}

'GUI Interfaces 
interface Menu {
    +displayMenu()
}
class ApplicantMenu extends Menu
class ManagerMenu extends Menu
class OfficerMenu extends Menu
class LoginMenu extends Menu {
    +displayMenu()
    'after login, we call one of the 3 menus based on the  enum 
}
LoginMenu ..> AppUserManager
LoginMenu ..> ApplicantMenu
LoginMenu ..> OfficerMenu
LoginMenu ..> ManagerMenu

'Arrays
class Users <<static>> implements ItemArray {
    -userArray:User[]
    +filter(p:Project,type:officer):Officer[]
    +filter(p:Project,type:manager):Manager[]
}
Users "1" -- "*" User

class Projects <<static>> implements ItemArray {
    -projectArray:Project[]
    +filter()
}
Projects "1" -- "*" Project

class Applications <<static>> implements ItemArray {
    -ApplicationArray:Application[]
    +filter(p:Project):Application[]
    +filter(a:Applicant):Application[]
}
Applications "1" -- "*" Application

class OfficerApplications <<static>> extends Applications implements ItemArray 
OfficerApplications "1" -- "*" OfficerApplication

class Enquiries <<static>> implements ItemArray {
    -EnquiryArray: Enquiry[]
    +filter(p:Project):Enquiry[]
}
Enquiries "1" -- "*" Enquiry

'Managers
class ApplicationManager <<static>> {
    +WithdrawApplication(a:Application)
    +ApproveApplication(a:Application)
    +BookApplication(a:Application)
    +ApproveWithdrawal(a:Application)
}
ApplicationManager ..> Application

class ProjectManager <<static>> {
    +newProject():Project
    +toggleVisibility(p:Project,vis:bool)
    +viewDetails(p:Project)
}
ProjectManager ..> Project

class EnquiryManager <<static>> {
    +reply(r:string) only used by managers
}
EnquiryManager ..> Enquiry

class AppUserManager <<static>> {
    -currentUser:User
    +login()
    +logout()
}
AppUserManager ..> User


' not sure about this one
class OfficerMenu extends ApplicantMenu 


@enduml